# OpenTelemetry Collector Configuration
# For collecting traces, metrics, and logs from conn-dict

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.name
        value: rsfn-connect
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

exporters:
  # Console exporter for development
  logging:
    loglevel: debug

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

  # OTLP exporter (can be configured to send to Jaeger, etc.)
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging, prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]

  extensions: []

  telemetry:
    logs:
      level: debug
